
    // This file is auto-generated by react-native-sbermarket-engine
    
    export default {
      'demo-module-a': () => require('demo-module-a').default,
  'demo-module-b': () => require('demo-module-b').default
    };
    